name: New Issue
description: Create New Issue
title: "Visit ABC or XYZ instead"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! [Code of Conduct](https://example.com). 
  - type: checkbox
